kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    app: {{ .Release.Name }} #内置变量引用定义集群名称
  name: {{ .Release.Name }} #同上
  namespace: {{ .Release.Namespace }} #内置变量引用Namespace
spec:
  replicas: {{ .Values.replicaCount }} #定义副本数,指定values.yaml文件定义的变量
  selector:
    matchLabels:  #管理statefulset 的labels名称,可用外部文件helpers.tpl中的函数变量
      {{- include "rabbitmq-cluster.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Values.headlessService.name }} #引用values.yaml定义的变量,用于集群内部通讯
  template:
    metadata:
      labels:  #管理pod的labels名称,可用外部helpers.tpl中的函数变量
        {{- include "rabbitmq-cluster.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - -c
        - cp -v /etc/rabbitmq/rabbitmq.conf ${RABBITMQ_CONFIG_FILE}; exec docker-entrypoint.sh
          rabbitmq-server
        command:
        - sh
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: rmq-cluster-secret
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: rmq-cluster-secret
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              key: cookie
              name: rmq-cluster-secret
        - name: K8S_SERVICE_NAME
          value: {{ .Values.headlessService.name }} #修改headlesssservice的service名称
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: RABBITMQ_NODENAME
          value: rabbit@$(POD_NAME).{{ .Values.headlessService.name }}.$(POD_NAMESPACE).svc.cluster.local
        - name: RABBITMQ_CONFIG_FILE
          value: /var/lib/rabbitmq/rabbitmq.conf
        image: {{ .Values.image.address }} #定义rabbitmq镜像下载地址
        imagePullPolicy: {{ .Values.image.pullPolicy }} #定义经镜像下载策略
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 30
          timeoutSeconds: 10
        name: rabbitmq #镜像名称
        ports:
        - containerPort: 15672
          name: http
          protocol: TCP
        - containerPort: 5672
          name: amqp
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /etc/rabbitmq
          name: config-volume
          readOnly: false
#        - mountPath: /var/lib/rabbitmq
#          name: rabbitmq-storage
#          readOnly: false
      serviceAccountName: rmq-cluster
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          - key: enabled_plugins
            path: enabled_plugins
          name: rmq-cluster-config
        name: config-volume
#  volumeClaimTemplates:
#  - metadata:
#      name: rabbitmq-storage
#    spec:
#      accessModes:
#      - ReadWriteMany
#      storageClassName: "rmq-storage-class"
#      resources:
#        requests:
#          storage: 4Gi
