kind: Secret
apiVersion: v1
metadata:
  name: rmq-cluster-secret
  namespace: {{ .Release.Namespace }} #定义内置变量namespace
stringData:
  cookie: ERLANG_COOKIE
  password: {{ .Values.password }} # 定义values.yaml文件变量
  url: amqp://{{ .Values.username }}:{{ .Values.password }}@{{ .Values.loadbalancerService.name }}
  username: {{ .Values.username }}
type: Opaque
